[FEAT] Add new fail_on_warnings to the coding-standard action
mage-os/github-actions pull request #132
Opened 2023-09-15 12:39 UTC by vitaliy-golomoziy

A PR for the issue https://github.com/mage-os/github-actions/issues/130

2023-09-15 12:47 UTC, damienwebdev requested changes
```
--config-set ignore_warnings_on_exit 1
```

Is better than changing the warning severity I think. 

This way, it will still echo out the warnings, but we won't get the non-zero exit status.

2023-09-15 13:35 UTC, damienwebdev commented
We'll need to allow the plugin by the demo package: https://github.com/mage-os/github-actions/blob/main/_test/demo-package/composer.json#L44

2023-09-15 14:28 UTC, damienwebdev requested changes

2023-09-15 14:28 UTC, damienwebdev commented on _test/demo-package/composer.json
> +	    "dealerdirect/phpcodesniffer-composer-installer": true
This can be removed.

2023-09-15 14:28 UTC, damienwebdev commented on coding-standard/action.yml
> +    description: 'Whether action should fail on warnings or not, default to true (fails)'
Grammar.

> Whether or not the action should fail on warnings, defaults to true (fails on warnings)

2023-09-15 14:43 UTC, damienwebdev approved these changes
lgtm

2023-09-15 14:44 UTC, damienwebdev requested changes

2023-09-15 14:44 UTC, damienwebdev commented on coding-standard/action.yml
> +    default: 1
Could this be `true` instead of `1`. While I am a robot, not everyone else is!

2023-09-19 12:10 UTC, vitaliy-golomoziy commented
@damienwebdev, please review

2023-09-19 13:00 UTC, damienwebdev requested changes

2023-09-20 13:44 UTC, damienwebdev commented on semver-compare/action.yml
> +    value: ${{ steps.semver-compare.outputs.result }}
@vitaliy-golomoziy bump on this.

2023-09-20 13:46 UTC, damienwebdev commented
Lookl like this PR has to be split into smaller PRs because of dependencies, the `@main` usage of a currently non-existing action inside of `coding-standard.yml` is failing the pipeline.

2023-09-20 13:48 UTC, damienwebdev requested changes
Looks like this PR has to be split into smaller PRs because of dependencies, the `@main` usage of a currently non-existing action inside of `coding-standard.yml` is failing the pipeline.

`get-composer-version` and `semver-compare` look good to me, so these can be split and merged quickly.

2023-09-20 13:51 UTC, vitaliy-golomoziy commented on semver-compare/action.yml
> +    value: ${{ steps.semver-compare.outputs.result }}
Correct, and also missed the README.md update, fixed both now.

2023-09-21 12:13 UTC, damienwebdev commented
Closing in favor of #145 #146 and #147

2023-09-21 12:13 UTC, closed without merging